#!/bin/sh
#
# @name my Custer airframe
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 motor LW
# @output MAIN2 motor RW
# @output MAIN3 front motor servo
# @output MAIN4 (aileron L) or BEC in
# @output MAIN5 aileron R
# @output MAIN6 elevator L
# @output MAIN7 elevator R
# @output MAIN8 rudders (& steering wheel)
#
# @maintainer Juraj Mihalik <jm1e16@soton.ac.uk>
#

set VEHICLE_TYPE fw
param set MAV_TYPE 1

if [ $AUTOCNF = yes ]
then
	param set PWM_MAIN_DIS1 950
	param set PWM_MAIN_FAIL1 950
	param set PWM_MAIN_MIN1 1000
	param set PWM_MAIN_MAX1 2000

	param set PWM_MAIN_DIS2 950
	param set PWM_MAIN_FAIL2 950
	param set PWM_MAIN_MIN2 1000
	param set PWM_MAIN_MAX2 2000

	param set PWM_MAIN_DIS3 1100
	param set PWM_MAIN_FAIL3 1100
	param set PWM_MAIN_MIN3 1300
	param set PWM_MAIN_MAX3 1850

	param set PWM_MAIN_DIS4 1500
	param set PWM_MAIN_FAIL4 1500
	param set PWM_MAIN_MIN4 1050
	param set PWM_MAIN_MAX4 1950

	param set PWM_MAIN_DIS5 1500
	param set PWM_MAIN_FAIL5 1500
	param set PWM_MAIN_MIN5 1050
	param set PWM_MAIN_MAX5 1950

	param set PWM_MAIN_DIS6 1500
	param set PWM_MAIN_FAIL6 1500
	param set PWM_MAIN_MIN6 1000
	param set PWM_MAIN_MAX6 2000

	param set PWM_MAIN_DIS7 1500
	param set PWM_MAIN_FAIL7 1500
	param set PWM_MAIN_MIN7 1000
	param set PWM_MAIN_MAX7 2000

	param set PWM_MAIN_DIS8 1500
	param set PWM_MAIN_FAIL8 1500
	param set PWM_MAIN_MIN8 1000
	param set PWM_MAIN_MAX8 2000

	param set SDLOG_PROFILE 27
#
# Default parameters for fixed wing UAVs.
# here to avoid set pwm_rate to 50 and pwm_out 1234. may not matter if i overwrite it here but who knows
#
	param set COM_POS_FS_DELAY 5
	param set COM_POS_FS_EPH 25
	param set COM_POS_FS_EPV 50
	param set COM_POS_FS_GAIN 0
	param set COM_POS_FS_PROB 1
	param set COM_VEL_FS_EVH 5

	param set EKF2_ARSP_THR 8
	param set EKF2_FUSE_BETA 1
	param set EKF2_GPS_CHECK 21
	param set EKF2_MAG_ACCLIM 0
	param set EKF2_MAG_YAWLIM 0
	param set EKF2_REQ_EPH 10
	param set EKF2_REQ_EPV 10
	param set EKF2_REQ_HDRIFT 0.5
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 1.0

	param set RTL_RETURN_ALT 50
	param set RTL_DESCEND_ALT 50
	param set RTL_LAND_DELAY -1

	#
	# FW uses L1 distance for acceptance radius.
	# Set a smaller NAV_ACC_RAD for vertical acceptance distance.
	#
	param set NAV_ACC_RAD 10

	param set MIS_LTRMIN_ALT 25
	param set MIS_TAKEOFF_ALT 25

	#
	# FW takeoff acceleration can easily exceed ublox GPS 2G default.
	#
	param set GPS_UBX_DYNMODEL 8
fi

set MIXER my_LQR_Custer
set MIXER_AUX my_LQR_Custer
param set PWM_RATE 200
param set PWM_AUX_RATE 200
set PWM_OUT 12345678
set PWM_AUX_OUT 1234 # group 0

my_LQR_control start -p 2

